# Generated by Django 3.2.8 on 2021-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productsubcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
