# Generated by Django 3.2.8 on 2021-10-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_promotion_discount_percentage'),
        ('authentication', '0002_user_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='TredingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.categoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.CharField(max_length=256)),
                ('banner_text', models.CharField(blank=True, max_length=256, null=True)),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.promotion')),
            ],
        ),
    ]
