# Generated by Django 3.2.8 on 2021-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_banner_tredingproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
