# Generated by Django 3.2.8 on 2021-10-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211030_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tredingproduct',
            old_name='product',
            new_name='trending_product',
        ),
    ]
