# Generated by Django 3.2.8 on 2021-10-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ABGDG', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
