# Generated by Django 3.2.8 on 2021-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='max_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='min_cart_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_type',
            field=models.IntegerField(choices=[(1, 'Percentage'), (2, 'Fixed')], default=1),
            preserve_default=False,
        ),
    ]
