# Generated by Django 3.2.8 on 2021-10-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_status'),
        ('cart', '0004_auto_20211018_0034'),
    ]

    operations = [
    ]
