# Generated by Django 3.2.8 on 2021-10-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_merge_0004_alter_order_status_0004_auto_20211018_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
