# Generated by Django 3.2.8 on 2021-11-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_offers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
