# Generated by Django 3.2.8 on 2021-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_offers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='term_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
