# Generated by Django 3.2.8 on 2021-11-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20211115_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'FAILED'), (3, 'SUCCESS'), (4, 'REFUND')], default=1),
        ),
    ]
