# Generated by Django 3.2.8 on 2021-11-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-id']},
        ),
    ]
